// Define your messages
const messages = {


    //--------------------------------------- Admin Messages-------------------------------
    ADMIN_NOT_FOUND: 'Admin Not Found',
    USER_NOT_FOUND: 'User Not Found',
    INVALID_EMAIL_PASSWORD: 'Invalid email or password',
    EMAIL_ALREADY_EXIST: 'Email Alraedy Exist',
    REGISTRATION_FAILED: 'User Register Failed',
    REGISTRATION_SUCCESSFUL: 'User Register Successfully',
    LOGIN_SUCCESSFUL: 'Login Successful',
    VERIFY_EMAIL_FIRST: 'Please Verify your email first',
    INVALID_EXPIRED_TOKEN: 'Invalid or expired token',
    PASSWORD_CAN_NOT_SAME: 'Password cannot be the same as the previous password.',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully.',
    PASSWORD_RESET_FAILED: 'Failed to reset password.',
    ADMIN_PROFILE_FETCHED: 'Admin profile fetched successfully',
    USER_PROFILE_FETCHED: 'User profile fetched successfully',
    CUREENT_NEW_REQUIERED: 'Current password and new password are required, and new password must be at least 8 characters long.',
    CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect.',
    PASSWORD_CAN_NOT_BE_SAME: 'Password cannot be the same as the previous password.',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
    USER_NOT_FOUNT: 'Users Not Found',
    SELLER_NOT_FOUNT: 'Sellers Not Found',
    USER_RETRIVED: 'Users Retrived Successfully!',
    SELLER_RETRIEVED: 'Sellers Retrived Successfully!',
    SUPPORT_NOT_FOUND: 'Supports Not Found',
    SUPPORT_RETRIVED: 'Supports Retrived Successfully',
    DASHBOARD_DATA_RETRIVED: 'Dashboard data retrieved successfully',
    PRODUCT_RETRIVED: 'Products Retrived Successfully!',
    POST_RETRIVED: 'Posts Retrived Successfully!',
    POST_NOT_FOUND: 'Post Not Found',
    POST_DELETED: 'Post Deleted Successfully!',
    SELF_STORAGE_ADDED: 'Self Storage Added Successfully',
    FORM_DATA_ADDED: 'Form Data Added Successfully',
    FORM_DATA_UPDATED: 'Form Data Updated Successfully',
    FORM_DATA_NOT_FOUND: 'Form Data Not Found',
    SELF_STORAGE_UPDATED: 'Self Storage Updated Successfully',
    STORAGE_NOT_FOUND: 'Self Storage Not Found',
    GET_SELF_STORAGES: 'Self Storage Retrived Successfully',
    GET_FORM_DATA: 'From Data Retrived Successfully',
    SELF_STORAGE_DELETED: 'Self Storage Deleted Successfully',
    GET_CONTACT_US: 'Contact Us Retrived Successfully',
    CONTACT_US_ADDED: 'Contact Us Sent Successfully',
    CONTACT_US_DELETED: 'Contact Us Deleted Successfully',
    CONTACT_US_NOT_FOUND: 'Contact Us Not Found',
    PASSWORD_RESET_LINK_SENT: (email) => `Password reset link sent to your email (${email}).`,
    USER_SUSPEND_UNSUSPENDED: (response_message) => `User ${response_message} Successfully`,
    SELLER_APPOROVE_REJECT: (response_message) => `Seller ${response_message} Successfully`,

};

export default messages;
